######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 20 11:18:17 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . avr LCD LCD/include
INCLUDEPATH += . avr

# Input
HEADERS += ardu.h \
           emulino-gui.h \
           avr/io.h \
           avr/pgmspace.h \
           LCD/KK2LCD.h \
           ../../../.arduino/sketchbook/libraries/KK2LCD/include/fonts.h \
           ../../../.arduino/sketchbook/libraries/KK2LCD/include/io_cfg.h \
           ../../../.arduino/sketchbook/libraries/KK2LCD/include/logo.h \
           ../../../.arduino/sketchbook/libraries/KK2LCD/include/st7565.h \
           ../../../.arduino/sketchbook/libraries/KK2LCD/include/typedefs.h \
           /usr/share/arduino/hardware/arduino/cores/arduino/WString.h \
           lcd.inc
SOURCES += ardu.c \
           conv.c \
           emulino-gui.cpp \
           main-gui.c \
           main.c \
           LCD/KK2LCD.c \
           ../../../.arduino/sketchbook/libraries/KK2LCD/include/font12x16.c \
           ../../../.arduino/sketchbook/libraries/KK2LCD/include/font12x24Number.c \
           ../../../.arduino/sketchbook/libraries/KK2LCD/include/font5x7.c \
           ../../../.arduino/sketchbook/libraries/KK2LCD/include/st7565.c \
           /usr/share/arduino/hardware/arduino/cores/arduino/WString.cpp
